### ISSUE TITLE
Repeated runs for NM150/NM200 is broken in Day 3 

### ISSUE THREAD

**Issue by dislyst** [steve1316/granblue-automation-pyautogui#195]
Hello, first of all thanks for the bot, it made my grinding easier but i encounter some issues with the bot in this guild war, so for some reason when NM 200 is available (Day 3 + 4) the bot refuses to run those quest, including NM 150, heres the error i encounter, i have meat at least 25k+ so the error doesnt make any sense, also i attach the log files if you need one, oh the bot is working fine yesterday but today it broke.
My monitor resolution is 1080p. 
Thanks.
![Granblue_Automation_HoMJN7wgK0](https://user-images.githubusercontent.com/72685998/234153812-c3edb105-2ab3-4f8a-a80c-3309010dbd4f.png)
[log 2023-04-25 09-39-30.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/11315717/log.2023-04-25.09-39-30.txt)

**Comment by steve1316** [comment]
Hmm, strange. I have NM150 and NM200 available as well and the bot is able to find and start both of them. From your logs, it was able to bring up the United Battle popup but was unable to find the two NMs on screen right afterwards. It falls back to meat farming if it could not find any NMs on the screen so that message about lacking meats is misleading.

It also could not close out the popup which is weird. Perhaps lowering your confidence levels and/or increasing the general tries in the Adjustments page may help.

**Comment by dislyst** [comment]
kay, will try to do that first, t

**Comment by dislyst** [comment]
Okay, setting the confidence level for multiple matching to 0.65 solved it, thanks for the advice, really appreciate it.
