### ISSUE TITLE
Turn waiting charged attack

### ISSUE THREAD

**Issue by zorkings** [steve1316/granblue-automation-pyautogui#3]
I've noticed when I have charged attacks going in a turn it tries to start the next turn whilst they are still going off.

Also suggest to add a full auto functionality because some quests/raids for me personally are full auto anyway

Just noticed bot is unable to detect quest button I believe due to strike time, will test more and find out.

**Comment by steve1316** [comment]
Currently, the bot waits 3 + (# of charge attacks) seconds whenever it clicks the Attack button. I think this is too fast considering what happened to yours. I will see towards adding a section in the config.ini that will allow users to customize the "__ + (# of charge attacks) seconds" so that if the default 3 is too fast, then you can change it to be longer. If you want, you can post the saved log here when this occurs so I can get a better idea of what happens.

Also, I added Full Auto functionality about 5 hours ago and updated the Combat Scripting Documentation and Examples page in the project wiki with documentation and examples of how to use it. Check it out and see if any problems occurs!

Finally yes, you are correct in noticing that it does not detect the Quest button when there is strike time because the crew that I am in does not have a strike time when I am awake so I have not had the chance to do so. If you can, can you take a screenshot of your Quest button while you are in strike time and post it in this thread? I would greatly appreciate it!

**Comment by zorkings** [comment]
My strike time ended about an hour ago, sorry! Very nice on the auto functionality will give it a try, did not see the update.

**Comment by zorkings** [comment]
Adding to this since its open, have found if the bot wipes in a raid it fails to retreat the 2nd pop asking if you would wish to full elixir

**Comment by zorkings** [comment]
> Currently, the bot waits 3 + (# of charge attacks) seconds whenever it clicks the Attack button. I think this is too fast considering what happened to yours. I will see towards adding a section in the config.ini that will allow users to customize the "__ + (# of charge attacks) seconds" so that if the default 3 is too fast, then you can change it to be longer. If you want, you can post the saved log here when this occurs so I can get a better idea of what happens.
> 
> Also, I added Full Auto functionality about 5 hours ago and updated the Combat Scripting Documentation and Examples page in the project wiki with documentation and examples of how to use it. Check it out and see if any problems occurs!
> 
> Finally yes, you are correct in noticing that it does not detect the Quest button when there is strike time because the crew that I am in does not have a strike time when I am awake so I have not had the chance to do so. If you can, can you take a screenshot of your Quest button while you are in strike time and post it in this thread? I would greatly appreciate it!

![image](https://user-images.githubusercontent.com/77841008/105918891-b81c5e00-6002-11eb-95b0-826a5682392d.png)

**Comment by steve1316** [comment]
Just pushed updates that should fix the bugs where:
- The party wipes during a Raid and it fails to back out properly, failing at the Full Elixir popup.
- The bot executed actions when the Turn has not started yet.
- The bot not detecting the Quest button during Strike Time.

Let me know how these worked out for you!

**Comment by zorkings** [comment]
> Just pushed updates that should fix the bugs where:
> 
> * The party wipes during a Raid and it fails to back out properly, failing at the Full Elixir popup.
> * The bot executed actions when the Turn has not started yet.
> * The bot not detecting the Quest button during Strike Time.
> 
> You can also now adjust the idling times when executing a skill/summon in the config.ini. Let me know how these worked out for you!

Strike time works fine now.
The party wipe worked to some point but bugged out, will need to watch / reproduce

Have found that during party selection if the raid ends it gets stuck in this loop with this pop up available

![image](https://user-images.githubusercontent.com/77841008/106237268-73dcb980-61cc-11eb-845f-a5b3cc2d527b.png)

**Comment by steve1316** [comment]
Completely forgot to tell the bot to press OK when that popup shows up. Just pushed an update fixing that. Have not been able to test it as all my raids so far have not finished before the bot joined them. Please let me know how it works out!

I will be closing this issue with this comment as the original bugs that started this have been fixed. Please feel free to open up another one when you encounter another bug or an existing one comes back like the party wipe bug and you are able to provide more information.
