### ISSUE TITLE
Stuck at support selection

### ISSUE THREAD

**Issue by KoiKomei** [steve1316/granblue-automation-pyautogui#62]
As per title, it seems that the bot gets stuck during summon selection for no reason, it clicks on the element and then just stalls infinitely, I don't know what might be the cause, it happens randomly.

![Screenshot_83](https://user-images.githubusercontent.com/32816781/130474595-7a0a79c3-21f4-4cef-a847-20ac24bfdd5d.png)

Update: it seems that sometimes it just skips every support image except the last summon
![Screenshot_500](https://user-images.githubusercontent.com/32816781/130494254-273dbfec-1613-45bd-8328-4103e944e947.png)

**Comment by steve1316** [comment]
I reworked the Summon Selection system recently.

The old method was searching one summon at a time. If it reached the bottom of the page, then it will scroll all the way back up and do the same thing again for the next summon. If it reaches the bottom of the page and none of your summons were detected, then it will reset summons.

The new method now searches for all summons simultaneously. If there are no summons that you picked on the screen, then it will scroll once and then searches for all summons simultaneously again, then repeat, etc until it reaches the bottom of the page and then it will reset summons.

I did this to save time if your 4th summon was already at the top of the page and saves time that way instead of scrolling all the way down 3 more times.

I will test it more on my end to see if the bot gets stuck infinitely due to this.

**Comment by KoiKomei** [comment]
Quite weird, I'll do more through tests whenever I get free. 
I'd also have to say that this behaviour happens ONLY on my laptop, so it might be some bug/unintended behaviour with the image recognition library.

Will keep you updated.

**Comment by NeapolitanIcecream** [comment]
Experiencing the same problem. Did not observe the scrolling nor logs reporting errors.

**Comment by steve1316** [comment]
Thank you for the simple fix! Merged your pull request.
