### ISSUE TITLE
Room search bug bot!

### ISSUE THREAD

**Issue by TheMan13579** [steve1316/granblue-automation-pyautogui#66]
![image](https://user-images.githubusercontent.com/38368285/131127771-22b950ef-611f-4085-a906-349b1142f210.png)
I have a developer twitter account, which has been verified. I have done all the steps you suggested but still get the above error.

**Comment by steve1316** [comment]
Hmm, it seems that your access key, access key secret, access token, and/or access token secret might be incorrect. When you generate your API key, try copying and pasting it in their relevant fields without enclosing them in quotes. 

It also could be a case of an accidental space somewhere in the fields. Having a space in front of the equals sign is fine.

If your keys and access tokens are the same in both the config.ini and on Twitter Developer Portal, then you may have been rate-limited due to turning on and turning off the bot repeatedly in a short period of time with the bot constantly connecting to the API for each attempt. Waiting a bit should allow you to be not rate-limited anymore.

**Comment by TheMan13579** [comment]
It still doesn't work my friend.

**Comment by steve1316** [comment]
Maybe try regenerating your keys and tokens again and replacing those in your config.ini with the new ones? Aside from that, I do not know how to resolve your issue.
